PlotlyDjango/PlotlyDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view( url='/irrigation_model/'), name='index'),

    # very unique way of specifying a path below.
    path('irrigation_model/', include(('irrigation_model.urls', 'irrigation_model'), namespace='irrigation_model', )),
]

PlotlyDjango/irrigation_model/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cropwateruse/', views.CropView.as_view(), name='Crop'),
]

PlotlyDjango/irrigation_model/models.py
from django.db import models

# Create your models here.

PlotlyDjango/irrigation_model/views.py
from django.shortcuts import render

# Create your views here.
# from django.http import HttpResponse,
from django.views.generic import TemplateView
from . import graphs

class IndexView(TemplateView):
    template_name = 'index.html'


class CropView(TemplateView):
    template_name = 'crop.html'

    def get_context_data(self, **kwargs):
        context = super(CropView, self).get_context_data(**kwargs)
        context['crop'] = graphs.plot_Cropwateruse()
        return context

PlotlyDjango/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Vaccine</title>

    <link rel="stylesheet" type="text/css" href="css/democss.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js" integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA==" crossorigin=""></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.js"></script>
    <script src="https://unpkg.com/esri-leaflet@2.2.3/dist/esri-leaflet.js" integrity="sha512-YZ6b5bXRVwipfqul5krehD9qlbJzc6KOGXYsDjU9HHXW2gK57xmWl2gU6nAegiErAqFXhygKIsWPKbjLPXVb2g==" crossorigin=""></script>
    <link rel="stylesheet" href="https://unpkg.com/esri-leaflet-geocoder@2.2.13/dist/esri-leaflet-geocoder.css" integrity="sha512-v5YmWLm8KqAAmg5808pETiccEohtt8rPVMGQ1jA6jqkWVydV5Cuz3nJ9fQ7ittSxvuqsvI9RSGfVoKPaAJZ/AQ==" crossorigin="">
    <script src="https://unpkg.com/esri-leaflet-geocoder@2.2.13/dist/esri-leaflet-geocoder.js" integrity="sha512-zdT4Pc2tIrc6uoYly2Wp8jh6EPEWaveqqD3sT0lf5yei19BC1WulGuh5CesB0ldBKZieKGD7Qyf/G0jdSe016A==" crossorigin=""></script>

    <script type="text/javascript" src="js/map.js"></script>
    {% endblock %}
</head>
<body onload="mapDisplay()">
{% block content %}
<!-- content goes here -->
{% endblock %}

{% block tail %}
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

{% endblock %}
</body>
</html>

PlotlyDjango/templates/crop.html
{% extends "base.html" %}
{% block title %} D3 Figure {% endblock %}

{% block head %}
{{block.super}}
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock %}

{% block content %}

<div class="container">
    <h1>Plot using Plot.ly</h1>
    <p class="lead">Here we go...</p>
</div>
<!-- /.container -->

<div class="container">
    <div class="row" style="border: 1px solid black">
        {# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
        <div class="col-md-12">{{crop|safe}}</div>
    </div>
</div>
<!-- /.container -->


<div class="container">
    <p>
        &nbsp;
    </p>
    <a class="btn btn-primary pull-right" href="{% url 'index' %}"> Go back to index...</a>
</div>
{% endblock %}

PlotlyDjango/templates/index.html
{% extends "base.html" %}

{% block content %}
<div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">VACCINE Lab</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
<div class="row">
    <!--<h1 style="text-align: center;"> Vaccine!</h1>-->
</div>

<div>
    <div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">zone information </a></li>
            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">input form </a></li>
            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Irrigation Model</a></li>
            <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Decisition path</a></li>
        </ul>


        <!-- Tab panes -->
        <div class="tab-content">

            <div role="tabpanel" class="tab-pane active" id="home">
                <!--<div id="mapid" style="width: 70%; height: 70%; position: relative; right:0; top:0%; border: black solid 1px; overflow: auto;"></div>-->
                <!--<div id="mapid" style="width: 100%; height: 100%; position: absolute; right:0%; top: 0%; border: black solid 1px; overflow: auto;"></div>-->
                <div id="mapid" style=" width: 100%; height: 100%; position: absolute;  border: black solid 1px; overflow: auto;"></div>


            </div>

            <div role="tabpanel" class="tab-pane" id="profile">

                <div class="col-sm-offset-3 col-sm-6">
                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                </div>

            </div>
            <div role="tabpanel" class="tab-pane" id="messages">
                <a class="btn btn-default" href="{% url 'irrigation_model:Crop' %}" role="button"> crop graph</a>

            </div>
            <div role="tabpanel" class="tab-pane" id="settings">4</div>

        </div>


    </div>
</div>

{% endblock %}